name: Build and Release CLI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile cli.py

      - name: Archive output
        uses: actions/upload-artifact@v2
        with:
          name: linux-cli
          path: dist/cli

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile cli.py

      - name: Archive output
        uses: actions/upload-artifact@v2
        with:
          name: windows-cli
          path: dist/cli.exe

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}  # Use the tag that triggered the workflow
          release_name: Release ${{ github.ref }}  # Use the tag name for the release name
          body: |
            - Linux binary: [cli](./dist/cli)
            - Windows binary: [cli.exe](./dist/cli.exe)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
